I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/humanite/amour/evts_rencontresAmoureuses.rpy", line 1, in script
    init -5 python:
  File "game/humanite/amour/evts_rencontresAmoureuses.rpy", line 1, in script
    init -5 python:
  File "game/humanite/amour/evts_rencontresAmoureuses.rpy", line 11, in <module>
    from humanite.amour import relationAmoureuse
IndentationError: unexpected indent (portrait.py, line 23)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 515, in main
    renpy.game.context().run(node)
  File "game/humanite/amour/evts_rencontresAmoureuses.rpy", line 1, in script
    init -5 python:
  File "game/humanite/amour/evts_rencontresAmoureuses.rpy", line 1, in script
    init -5 python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/humanite/amour/evts_rencontresAmoureuses.rpy", line 11, in <module>
    from humanite.amour import relationAmoureuse
  File "renpy/loader.py", line 985, in load_module
    exec(code, mod.__dict__)
  File "humanite/amour/relationAmoureuse.py", line 2, in <module>
  File "renpy/loader.py", line 979, in load_module
    code = compile(source, filename, 'exec', renpy.python.old_compile_flags, 1)
IndentationError: unexpected indent (portrait.py, line 23)

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
destinRoiClovis 1.0
Mon Jun 14 20:27:07 2021
